<?php

namespace Synerise\Api\V4\Models;

use Microsoft\Kiota\Abstractions\Serialization\AdditionalDataHolder;
use Microsoft\Kiota\Abstractions\Serialization\Parsable;
use Microsoft\Kiota\Abstractions\Serialization\ParseNode;
use Microsoft\Kiota\Abstractions\Serialization\SerializationWriter;

class TagAssociation implements AdditionalDataHolder, Parsable 
{
    /**
     * @var array<string, mixed>|null $additionalData Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    */
    private ?array $additionalData = null;
    
    /**
     * @var int|null $clientId Unique ID. This ID is generated by the system during profile creation.
    */
    private ?int $clientId = null;
    
    /**
     * @var int|null $id ID of the assignment
    */
    private ?int $id = null;
    
    /**
     * @var int|null $tagId ID of the tag
    */
    private ?int $tagId = null;
    
    /**
     * Instantiates a new TagAssociation and sets the default values.
    */
    public function __construct() {
        $this->setAdditionalData([]);
    }

    /**
     * Creates a new instance of the appropriate class based on discriminator value
     * @param ParseNode $parseNode The parse node to use to read the discriminator value and create the object
     * @return TagAssociation
    */
    public static function createFromDiscriminatorValue(ParseNode $parseNode): TagAssociation {
        return new TagAssociation();
    }

    /**
     * Gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     * @return array<string, mixed>|null
    */
    public function getAdditionalData(): ?array {
        return $this->additionalData;
    }

    /**
     * Gets the clientId property value. Unique ID. This ID is generated by the system during profile creation.
     * @return int|null
    */
    public function getClientId(): ?int {
        return $this->clientId;
    }

    /**
     * The deserialization information for the current model
     * @return array<string, callable(ParseNode): void>
    */
    public function getFieldDeserializers(): array {
        $o = $this;
        return  [
            'clientId' => fn(ParseNode $n) => $o->setClientId($n->getIntegerValue()),
            'id' => fn(ParseNode $n) => $o->setId($n->getIntegerValue()),
            'tagId' => fn(ParseNode $n) => $o->setTagId($n->getIntegerValue()),
        ];
    }

    /**
     * Gets the id property value. ID of the assignment
     * @return int|null
    */
    public function getId(): ?int {
        return $this->id;
    }

    /**
     * Gets the tagId property value. ID of the tag
     * @return int|null
    */
    public function getTagId(): ?int {
        return $this->tagId;
    }

    /**
     * Serializes information the current object
     * @param SerializationWriter $writer Serialization writer to use to serialize this model
    */
    public function serialize(SerializationWriter $writer): void {
        $writer->writeIntegerValue('clientId', $this->getClientId());
        $writer->writeIntegerValue('id', $this->getId());
        $writer->writeIntegerValue('tagId', $this->getTagId());
        $writer->writeAdditionalData($this->getAdditionalData());
    }

    /**
     * Sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     * @param array<string,mixed> $value Value to set for the AdditionalData property.
    */
    public function setAdditionalData(?array $value): void {
        $this->additionalData = $value;
    }

    /**
     * Sets the clientId property value. Unique ID. This ID is generated by the system during profile creation.
     * @param int|null $value Value to set for the clientId property.
    */
    public function setClientId(?int $value): void {
        $this->clientId = $value;
    }

    /**
     * Sets the id property value. ID of the assignment
     * @param int|null $value Value to set for the id property.
    */
    public function setId(?int $value): void {
        $this->id = $value;
    }

    /**
     * Sets the tagId property value. ID of the tag
     * @param int|null $value Value to set for the tagId property.
    */
    public function setTagId(?int $value): void {
        $this->tagId = $value;
    }

}
